### ISSUE TITLE
Missing column in database

### ISSUE THREAD

**Issue by jslirola** [Nearata/flarum-ext-related-discussions#1] opened 2023-01-29 07:18 UTC
First report on discuss: https://discuss.flarum.org/d/28996-related-discussions/168

I was curious to see the difference between this extension and the other related discussions so I tried to install it and I see that it is a bug when activating the extension and opening a discussion. In the initial migration that column does not exist.

```
Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nearataRelatedDiscussions' in 'field list' in /var/www/flarum_base/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
Stack trace:
#0 /var/www/flarum_base/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(87): Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
#1 /var/www/flarum_base/vendor/illuminate/database/Connection.php(522): Doctrine\DBAL\Driver\PDOConnection->prepare('update `discuss...')
#2 /var/www/flarum_base/vendor/illuminate/database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}('update `discuss...', Array)
#3 /var/www/flarum_base/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback('update `discuss...', Array, Object(Closure))
#4 /var/www/flarum_base/vendor/illuminate/database/Connection.php(533): Illuminate\Database\Connection->run('update `discuss...', Array, Object(Closure))
#5 /var/www/flarum_base/vendor/illuminate/database/Connection.php(466): Illuminate\Database\Connection->affectingStatement('update `discuss...', Array)
#6 /var/www/flarum_base/vendor/illuminate/database/Query/Builder.php(3063): Illuminate\Database\Connection->update('update `discuss...', Array)
#7 /var/www/flarum_base/vendor/illuminate/database/Eloquent/Builder.php(921): Illuminate\Database\Query\Builder->update(Array)
#8 /var/www/flarum_base/vendor/illuminate/database/Eloquent/Model.php(1072): Illuminate\Database\Eloquent\Builder->update(Array)
#9 /var/www/flarum_base/vendor/illuminate/database/Eloquent/Model.php(987): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder))
#10 /var/www/flarum_base/vendor/michaelbelgium/flarum-discussion-views/src/Listeners/AddDiscussionViewHandler.php(60): Illuminate\Database\Eloquent\Model->save()
#11 /var/www/flarum_base/vendor/flarum/core/src/Foundation/ContainerUtil.php(30): Michaelbelgium\Discussionviews\Listeners\AddDiscussionViewHandler->__invoke(Object(Flarum\Api\Controller\ShowDiscussionController), Object(Flarum\Discussion\Discussion), Object(Laminas\Diactoros\ServerRequest), Object(Tobscure\JsonApi\Document))
#12 /var/www/flarum_base/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(121): Flarum\Foundation\ContainerUtil::Flarum\Foundation\{closure}(Object(Flarum\Api\Controller\ShowDiscussionController), Object(Flarum\Discussion\Discussion), Object(Laminas\Diactoros\ServerRequest), Object(Tobscure\JsonApi\Document))
#13 /var/www/flarum_base/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\AbstractSerializeController->handle(Object(Laminas\Diactoros\ServerRequest))
#14 /var/www/flarum_base/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Laminas\Diactoros\ServerRequest), Array)
#15 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Closure))
#16 /var/www/flarum_base/vendor/kilowhat/flarum-ext-audit-free/src/Middlewares/SetLoggerActor.php(28): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#17 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Kilowhat\Audit\Middlewares\SetLoggerActor->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#18 /var/www/flarum_base/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#19 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Api\Middleware\ThrottleApi->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#20 /var/www/flarum_base/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#21 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CheckCsrfToken->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#22 /var/www/flarum_base/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#23 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ResolveRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#24 /var/www/flarum_base/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#25 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\SetLocale->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#26 /var/www/flarum_base/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(58): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#27 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#28 /var/www/flarum_base/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#29 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#30 /var/www/flarum_base/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#31 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\RememberFromCookie->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#32 /var/www/flarum_base/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#33 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\StartSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#34 /var/www/flarum_base/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#35 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#36 /var/www/flarum_base/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#37 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ParseJsonBody->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#38 /var/www/flarum_base/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#39 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\HandleErrors->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#40 /var/www/flarum_base/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#41 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\InjectActorReference->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#42 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#43 /var/www/flarum_base/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#44 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\RequestHandler->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#45 /var/www/flarum_base/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#46 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePathRouter->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#47 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#48 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\OriginalMessages->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#49 /var/www/flarum_base/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#50 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePath->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#51 /var/www/flarum_base/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#52 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ProcessIp->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#53 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#54 /var/www/flarum_base/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\EmptyPipelineHandler))
#55 /var/www/flarum_base/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle(Object(Laminas\Diactoros\ServerRequest))
#56 /var/www/flarum_base/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#57 /var/www/html/public/forum/index.php(28): Flarum\Http\Server->listen()
#58 {main}
```

**Comment by Nearata** [comment] 2023-01-29 10:31
im not able to replicate this

the step i did:

1. install extension
2. php flarum migrate
3. php flarum cache:clear
4. visit a discussion

**Comment by CharlieLeee** [comment] 2023-01-29 10:53
Yeah, I have the same issue with @jslirola even after following the steps in https://github.com/Nearata/flarum-ext-related-discussions/issues/1#issuecomment-1407624728

**Comment by Nearata** [comment] 2023-01-29 11:20
can you confirm that the table doesnt exist in database?

**Comment by CharlieLeee** [comment] 2023-01-29 12:19
> can you confirm that the table doesnt exist in database?

I checked and found the table named `nearata_related_discussions` exists

**Comment by Nearata** [comment] 2023-01-29 13:46
try 1.1.1

**Comment by Nearata** [comment] 2023-01-29 13:55
@CharlieLeee you have https://packagist.org/packages/michaelbelgium/flarum-discussion-views extension too?

**Comment by CharlieLeee** [comment] 2023-01-29 14:12
> @CharlieLeee you have https://packagist.org/packages/michaelbelgium/flarum-discussion-views extension too?

Yes, I have discussion-views, and after trying 1.1.1 I still got 
```
[2023-01-29 05:57:01] flarum.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nearataRelatedDiscussions' in 'field list' in /www/wwwroot/folder/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82
Stack trace:
```

**Comment by Nearata** [comment] 2023-01-29 18:19
@CharlieLeee @jslirola should be fixed in 1.2.0

**Comment by CharlieLeee** [comment] 2023-01-29 18:29
> @CharlieLeee @jslirola should be fixed in 1.2.0

Yes, it's working as expected now! But an issue I met is if I view the page as a visitor, I got this error in the terminal of browser:
```
TypeError: Vnodes must either always have keys or never have keys!
    at e.normalizeChildren (vnode.js:21:11)
    at t.exports (hyperscript.js:93:26)
    at s (index.js:7:43)
    at n (patchMithril.js:7:33)
    at e.<anonymous> (index.js:88:12)
    at forEach.t.<computed> (extend.ts:86:24)
    at forEach.t.<computed> [as view] (extend.ts:37:41)
    at Function.a (render.js:30:16)
    at render.js:155:45
    at render.js:160:3
a @ mount-redraw.js:15
(anonymous) @ mount-redraw.js:25
requestAnimationFrame (async)
u @ mount-redraw.js:23
(anonymous) @ PostStreamState.ts:125
Promise.then (async)
e.goToNumber @ PostStreamState.ts:125
n.show @ DiscussionPage.tsx:227
forEach.t.<computed> @ extend.ts:37
Promise.then (async)
n.load @ DiscussionPage.tsx:169
n.oninit @ DiscussionPage.tsx:49
a @ render.js:30
j @ render.js:917
(anonymous) @ render.js:153
(anonymous) @ render.js:160
c @ render.js:66
l @ render.js:50
f @ render.js:374
(anonymous) @ render.js:444
p @ render.js:415
(anonymous) @ render.js:488
p @ render.js:419
f @ render.js:302
(anonymous) @ render.js:964
a @ mount-redraw.js:14
(anonymous) @ mount-redraw.js:25
requestAnimationFrame (async)
u @ mount-redraw.js:23
m @ router.js:111
Promise.then (async)
t @ router.js:126
E @ router.js:95
setTimeout (async)
n @ router.js:143
d @ router.js:20
y.set @ router.js:182
s.attrs.onclick @ router.js:250
M.handleEvent @ render.js:888
c @ rocket-loader.min.js:1
```

**Comment by Nearata** [comment] 2023-01-29 19:14
no clue. did you cleared cache?

**Comment by Nearata** [comment] 2023-01-29 19:30
@CharlieLeee moreover, that trace doesn't seems to be related to this issue/extension, and im not able to reproduce

**Comment by CharlieLeee** [comment] 2023-01-29 19:34
> @CharlieLeee moreover, that trace doesn't seems to be related to this issue/extension, and im not able to reproduce

Yes, the cache was cleared, maybe it's related to the anonymous extension 🤔

**Comment by jslirola** [comment] 2023-01-30 07:18
@Nearata Thanks! It works fine after the new update.

**Comment by CharlieLeee** [comment] 2023-01-30 10:37
> @Nearata Thanks! It works fine after the new update.

Could you please check if this issue https://github.com/Nearata/flarum-ext-related-discussions/issues/1#issuecomment-1407736694 exists on your side?

**Comment by jslirola** [comment] 2023-01-30 17:37
> Could you please check if this issue [#1 (comment)](https://github.com/Nearata/flarum-ext-related-discussions/issues/1#issuecomment-1407736694) exists on your side?

You are right, that error occurs in the browser console if you access a discussion as a guest.

**Comment by CharlieLeee** [comment] 2023-01-30 17:45
> > Could you please check if this issue [#1 (comment)](https://github.com/Nearata/flarum-ext-related-discussions/issues/1#issuecomment-1407736694) exists on your side?
> 
> You are right, that error occurs in the browser console if you access a discussion as a guest.

Do the discussions on that page show if there's error in the browser's console?

**Comment by jslirola** [comment] 2023-01-30 17:52
It shows the same error that you posted in your comment, I attach a screenshot:

![related_error](https://user-images.githubusercontent.com/6697559/215554861-552a41ff-2169-4cb5-aeec-9656f77cc8ae.png)

**Comment by Nearata** [comment] 2023-01-30 17:59
what's `InsertBetweenPostsAds.tsx` from? can you share your installed extensions? or even a working link if you can

**Comment by CharlieLeee** [comment] 2023-01-30 18:04
> what's `InsertBetweenPostsAds.tsx` from? can you share your installed extensions? or even a working link if you can

I believe it's related to `davwheat-ads` extension, despite disabling the 'davwheat-ads' extension, it still persists.

These are the extensions I use.
```
+------------------------------------------+------------+--------+
| Flarum Extensions                        |            |        |
+------------------------------------------+------------+--------+
| ID                                       | Version    | Commit |
+------------------------------------------+------------+--------+
| flarum-likes                             | v1.6.1     |        |
| flarum-tags                              | v1.6.1     |        |
| flarum-flags                             | v1.6.1     |        |
| flarum-suspend                           | v1.6.1     |        |
| flarum-subscriptions                     | v1.6.3     |        |
| antoinefr-money                          | v1.2.0     |        |
| flarum-markdown                          | v1.6.1     |        |
| flarum-sticky                            | v1.6.1     |        |
| flarum-bbcode                            | v1.6.0     |        |
| flarum-nicknames                         | v1.6.1     |        |
| fof-pages                                | 1.0.4      |        |
| flamarkt-backoffice                      | 0.1.3      |        |
| fof-byobu                                | 1.1.8      |        |
| fof-follow-tags                          | 1.1.7      |        |
| fof-polls                                | 1.3.0      |        |
| flarum-mentions                          | v1.6.3     |        |
| afrux-forum-widgets-core                 | v0.1.7     |        |
| ziiven-money-leaderboard                 | v0.1.2     |        |
| ziiven-daily-check-in                    | v0.3.6     |        |
| zequeen-acgembed-remastered              | v1.1.2     |        |
| v17development-seo                       | v1.8.0     |        |
| therealsujitk-gifs                       | v4.1.1     |        |
| the-turk-stickiest                       | 3.0.1      |        |
| the-turk-mathren                         | 1.0.7      |        |
| the-turk-flamoji                         | 1.0.4      |        |
| the-turk-diff                            | 1.1.2      |        |
| sycho-profile-cover                      | v1.3.3     |        |
| sycho-private-facade                     | v0.1.12    |        |
| swaggymacro-only-starter                 | 0.6.4      |        |
| pipecraft-id-slug                        | v1.1.0     |        |
| noriods-auto-more                        | v1.0.0     |        |
| migratetoflarum-fake-data                | 1.4.0      |        |
| michaelbelgium-discussion-views          | v7.2       |        |
| littlecxm-reply-to-see                   | 1.0.2      |        |
| justoverclock-guestengagement            | 1.0.3      |        |
| jslirola-login2seeplus                   | v0.2.1     |        |
| ianm-syndication                         | 1.2.2      |        |
| ianm-log-viewer                          | 0.1.1      |        |
| ianm-html-head                           | 1.1.0      |        |
| ganuonglachanh-sonic                     | 0.1.5      |        |
| fof-username-request                     | 1.0.1      |        |
| fof-user-bio                             | 1.1.1      |        |
| fof-upload                               | 1.2.3      |        |
| fof-terms                                | 1.2.0      |        |
| fof-sitemap                              | 2.0.1      |        |
| fof-reactions                            | 1.1.3      |        |
| fof-profile-image-crop                   | 1.0.1      |        |
| fof-pretty-mail                          | 1.1.1      |        |
| fof-oauth                                | 1.3.0      |        |
| fof-nightmode                            | 1.5.1      |        |
| fof-masquerade                           | 2.1.3      |        |
| fof-links                                | 1.1.2      |        |
| fof-linguist                             | 1.1.0      |        |
| fof-impersonate                          | 1.1.0      |        |
| fof-ignore-users                         | 1.1.0      |        |
| fof-forum-statistics-widget              | 1.0.2      |        |
| fof-formatting                           | 1.0.2      |        |
| fof-drafts                               | 1.2.2      |        |
| fof-doorman                              | 1.1.0      |        |
| fof-discussion-thumbnail                 | 1.1.0      |        |
| fof-default-user-preferences             | 1.2.0      |        |
| fof-cookie-consent                       | 1.1.1      |        |
| fof-best-answer                          | 1.2.4      |        |
| fof-analytics                            | 1.1.0      |        |
| flarumtr-mobile-search                   | v1.2       |        |
| flarum-statistics                        | v1.6.1     |        |
| flarum-pusher                            | v1.6.1     |        |
| flarum-lock                              | v1.6.1     |        |
| flarum-lang-english                      | v1.6.0     |        |
| flarum-lang-chinese-simplified           | v1.3.0     |        |
| flarum-emoji                             | v1.6.1     |        |
| ecnu-im-sticky-sidenav                   | v1.1.0     |        |
| davwheat-ads                             | 1.2.0      |        |
| datlechin-silent-edit                    | v0.1.0     |        |
| datlechin-more-discussions               | v0.1.0     |        |
| datlechin-link-preview                   | v1.2.1     |        |
| darkle-fancybox                          | 1.1.2      |        |
| club-1-cross-references                  | v0.4.1     |        |
| clarkwinkelmann-who-read                 | 1.4.1      |        |
| clarkwinkelmann-vote-with-money          | 1.0.0      |        |
| clarkwinkelmann-see-past-first-post      | 1.3.1      |        |
| clarkwinkelmann-money-rewards            | 1.0.0      |        |
| clarkwinkelmann-mailing                  | 1.0.0      |        |
| clarkwinkelmann-group-list               | 1.0.0      |        |
| clarkwinkelmann-group-invitation         | 1.0.2      |        |
| clarkwinkelmann-discussion-open-position | 1.1.0      |        |
| clarkwinkelmann-discussion-lists         | 1.0.0      |        |
| clarkwinkelmann-anonymous-posting        | 1.0.1      |        |
| blomstra-welcome-login                   | 0.1.0      |        |
| blomstra-database-queue                  | 0.1-beta.2 |        |
| askvortsov-rich-text                     | v2.1.7     |        |
| askvortsov-pwa                           | v3.1.3     |        |
| askvortsov-markdown-tables               | v1.2.1     |        |
| askvortsov-discussion-templates          | v0.8.3     |        |
| afrux-online-users-widget                | v0.1.6     |        |
| afrux-news-widget                        | v0.1.1     |        |
| acpl-mobile-tab                          | 1.1.1      |        |
+------------------------------------------+------------+--------+
```

**Comment by CharlieLeee** [comment] 2023-01-30 20:14
> try 1.2.1

I confirm it works perfect now! Thanks for the great work!

**Comment by jslirola** [comment] 2023-01-31 07:00
Yes, the issue can be closed now. Thanks again :)

**Comment by Nearata** [comment] 2023-01-31 10:11
Awesome!! Thank you both!

**Closed** 2023-01-31 10:11 UTC
